name: PublishDockerImage

on:
  release:
    types: [published]

jobs:
  generate:
    name: 'Update node-red-docker image'
    runs-on: ubuntu-latest
    steps:
      - name: Check out node-red repository
        uses: actions/checkout@v2
        with:
            path: 'node-red'
      - name: Check out node-red-docker repository
        uses: actions/checkout@v2
        with:
            repository: 'node-red/node-red-docker'
            path: 'node-red-docker'
      - uses: actions/setup-node@v1
        with:
            node-version: '12'
      - run: node ./node-red/.github/scripts/update-node-red-docker.js
        id: updateFiles
      - name: Check outputs
        run: |
          echo "Version number - ${{ env.newVersion }}"
